version: "3.9"

services:
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://todo:todo@db:5432/todo?sslmode=disable

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
